{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": true,
    "blocklist-url": "http://john.bitsurge.net/public/biglist.p2p.gz",
    "cache-size-mb": 20,
    "dht-enabled": true,
    "download-dir": "{{ DOWNLOAD_DIR }}",
    "download-queue-enabled": true,
    "download-queue-size": 6,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "{{ TRANSMISSION_HOME }}/downloads",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": {{ MESSAGE_LEVEL }},
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 1200,
    "peer-limit-per-torrent": 180,
    "peer-port": {{ PEER_PORT }},
    "peer-port-random-high": 51234,
    "peer-port-random-low": 51234,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": 1,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 1,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-password": "{{ RPC_PASSWORD }}",
    "rpc-port": {{ RPC_PORT }},
    "rpc-url": "/transmission/",
    "rpc-username": "{{ RPC_USERNAME }}",
    "rpc-whitelist": "127.0.0.1,192.168.*.*,10.*.*.*,172.*.*.*",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": true,
    "seed-queue-size": 3,
    "speed-limit-down": {{ SPEED_LIMIT_DOWN }},
    "speed-limit-down-enabled": {{ SPEED_LIMIT_DOWN_ENABLED }},
    "speed-limit-up": 3200,
    "speed-limit-up-enabled": true,
    "start-added-torrents": true,
    "trash-original-torrent-files": true,
    "umask": 0,
    "upload-slots-per-torrent": 10,
    "utp-enabled": true,
    "watch-dir": "{{ WATCH_DIR }}",
    "watch-dir-enabled": {{ WATCH_DIR_ENABLED }}
}