#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

echo "**** Starting Transmission (https://www.transmissionbt.com/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

# Generate the transmission monitor config from template and env vars
t2 /templates

echo "--> Checking special tun file ..."
[ -d /dev/net ] || mkdir -vp /dev/net
[ -c /dev/net/tun ] || {
  echo "--> Creating /dev/net/tun ..."
  mknod /dev/net/tun c 10 200
  chmod a+rw /dev/net/tun
}

exec $*
exit 0
